### PR TITLE
Add missing new metrics from HealthMetric enum

### PR DESCRIPTION
**Pull request by C-D-Lewis**
Two new items were added in 3.10. AppMode was removed as redundant since the enum is a linear scale.

### CODE REVIEW

**Comment by cat-haines** [comment]
A minor refactor, but :+1: otherwise.

**Comment by C-D-Lewis** [comment]
I also refactored the TextLayer code, mind reviewing once more?

**Comment by cat-haines** [comment]
A couple more tiny things.

**Comment by cat-haines** [comment]
:+1:

**Pull request merged**
